name: Generate RSS Feed

on:
  schedule:
    - cron: '0 */3 * * *' # Every 3 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate RSS feed
        run: npm run generate

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain docs/feed.xml)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/feed.xml
            git commit -m "chore: update RSS feed"
            git push
          else
            echo "No feed changes to commit."
          fi
